"""add hot score

Revision ID: 4f4a8c914911
Revises: 
Create Date: 2021-12-18 03:37:13.716502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4a8c914911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hot_score', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_post_comment_timestamp'), 'post', ['comment_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_comment_timestamp'), table_name='post')
    op.drop_column('post', 'hot_score')
    # ### end Alembic commands ###
