"""add author_title

Revision ID: 91e5c7d37d43
Revises: 4f4a8c914911
Create Date: 2021-12-23 17:31:49.909672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e5c7d37d43'
down_revision = '4f4a8c914911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_title', sa.String(length=10), nullable=True))
    op.add_column('post', sa.Column('author_title', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'author_title')
    op.drop_column('comment', 'author_title')
    # ### end Alembic commands ###
